name: timescaleanalysis
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - arpack=3.9.1=nompi_hf03ea27_102
  - beartype=0.22.6=pyhd8ed1ab_0
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - click=8.3.1=pyh707e725_0
  - contourpy=1.3.3=py312hd9148b4_3
  - cycler=0.12.1=pyhd8ed1ab_1
  - decorit=0.2.0=pyhd8ed1ab_0
  - fonttools=4.60.1=py312h8a5da7c_0
  - freetype=2.14.1=ha770c72_0
  - glpk=5.0=h445213a_0
  - gmp=6.3.0=hac33072_2
  - igraph=1.0.0=hfe3e89f_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py312h0a2e395_2
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - leidenalg=0.11.0=py312h1289d80_0
  - lerc=4.0.0=h0aef613_1
  - libblas=3.11.0=2_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=2_h0358290_openblas
  - libdeflate=1.25=h17f619e_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_13
  - libgcc-ng=15.2.0=h69a702a_13
  - libgfortran=15.2.0=h69a702a_13
  - libgfortran5=15.2.0=h68bc16d_13
  - libgomp=15.2.0=he0feb66_13
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=2_h47877c9_openblas
  - libleidenalg=0.12.0=hb700be7_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.51=h421ea60_0
  - libsqlite=3.51.0=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_13
  - libstdcxx-ng=15.2.0=hdf11a46_13
  - libtiff=4.7.1=h9d88235_1
  - libuuid=2.41.2=he9a06e4_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=h031cc0b_0
  - libxml2-16=2.15.1=hf2a90c1_0
  - libxml2-devel=2.15.1=h031cc0b_0
  - libzlib=1.3.1=hb9d3cd8_2
  - linkify-it-py=2.0.3=pyhd8ed1ab_1
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - matplotlib-base=3.10.8=py312he3d6523_0
  - mdit-py-plugins=0.5.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mosaic-clustering=0.5.0=pyhd8ed1ab_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - numpy=2.3.0=py312h6cf2f7f_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.1=h35e630c_1
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hf79963d_1
  - pillow=12.0.0=py312h898c6c0_1
  - pip=25.3=pyh8b19718_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prettypyplot=0.12.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.12.12=hd63d673_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-igraph=1.0.0=py312h1289d80_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - qhull=2020.2=h434a139_5
  - readline=8.2=h8c095d6_2
  - rich=14.2.0=pyhcf101f3_0
  - scipy=1.16.3=py312h7a1785b_1
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - texttable=1.7.0=pyhd8ed1ab_1
  - textual=6.6.0=pyhd8ed1ab_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tqdm=4.67.3=pyh8f84b5b_0
  - trogon=0.6.0=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - uc-micro-py=1.0.3=pyhd8ed1ab_1
  - unicodedata2=17.0.0=py312h4c3975b_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - zlib-ng=2.2.5=hde8ca8f_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
    - imageio==2.37.2
    - iniconfig==2.3.0
    - lazy-loader==0.4
    - llvmlite==0.46.0
    - networkx==3.6.1
    - numba==0.63.1
    - pluggy==1.6.0
    - pytest==9.0.2
    - pz==1.1.0
    - scikit-image==0.26.0
    - scikit-learn==1.8.0
    - tifffile==2026.1.28
prefix: /home/ed1022/anaconda3/envs/timescaleanalysis
